#!/bin/bash
#
# Hook script for QEMU
# 
# adds port forwards via IPtables to your VMs
#
# Erico Mendonca (erico.mendonca@suse.com)
# dec/2018
#

log() {
	logger -t addForward "$1"
}

addForward() {

   IPTABLES="/usr/sbin/iptables"
   VM=$1
   HOST_PORT=$2
   GUEST_IP=$3
   GUEST_PORT=$4

   if [ "${ACTION}" == "stopped" ] || [ "${ACTION}" == "reconnect" ]; then
	   IPTABLES_ACTION="-D"
   fi

   if [ "${ACTION}" == "start" ] || [ "${ACTION}" == "reconnect" ]; then
	   IPTABLES_ACTION="-I"
   fi

   if [ "${VM}" == "${VM_NAME}" ]; then

	   HOST_BRIDGE=$(virsh dumpxml ${VM} | xpath -e /domain/devices/interface[1]/source | cut -d\= -f3 | cut -d\" -f2)
	   if [ -z $HOST_BRIDGE ]; then
		   log "Could not identify bridge interface for VM ${VM}, skipping"
		   exit 0
	   fi

	   log "adding forwarding rules for VM ${VM_NAME}: host port ${HOST_PORT} will be redirected to ${GUEST_IP}:${GUEST_PORT} on interface ${HOST_BRIDGE}"
	   $IPTABLES ${IPTABLES_ACTION} FORWARD -o ${HOST_BRIDGE} -d $GUEST_IP -j ACCEPT
	   $IPTABLES -t nat ${IPTABLES_ACTION} PREROUTING -p tcp --dport $HOST_PORT -j DNAT --to $GUEST_IP:$GUEST_PORT
   fi
}

VM_NAME=${1}
ACTION=${2}

### declare your port forwards here
### format: <VM> <source port> <destination address> <destination port>
addForward caasp-admin 20022 192.168.101.200 22

